version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: dockerfile-dev
    image: qc-front-dev:debug
    ports:
      - "9001:9001"
    networks:
      - webnet


networks:
  webnet:
