export const comparators = [
  'equal: 等于',
  'not_equal: 不等于',
  'contains: 包含',
  'startswith: 以...开头',
  'endswith: 以...结尾',
  'contained_by: 实际结果是否被包含在预期结果中',
  'less_than: 小于',
  'less_or_equals: 小于等于',
  'greater_than: 大于',
  'greater_or_equals: 大于等于',
  'string_equals: 字符串相等',
  'length_equal: 长度等于',
  'length_greater_than: 长度大于',
  'length_greater_or_equals: 长度大于等于',
  'length_less_than: 长度小于',
  'length_less_or_equals: 长度小于等于',
  'type_match: 类型是否匹配',
  'regex_match: 字符串是否符合正则表达式匹配规则',
];

export const headers = [
  'Accept',
  'Accept-Charset',
  'Accept-Encoding',
  'Accept-Language',
  'Accept-DateTime',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Cookie',
  'Content-Disposition',
  'Content-Length',
  'Content-MD5',
  'Content-Type',
  'Date',
  'Expect',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Max-Forwards',
  'Origin',
  'Pragma',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'TE',
  'User-Agent',
  'Upgrade',
  'Via',
  'Warning',
  'X-Requested-With',
  'DNT',
  'X-Forwarded-For',
  'X-Forwarded-Host',
  'X-Forwarded-Proto',
  'Front-End-Https',
  'X-Http-Method-Override',
  'X-ATT-Deviceld',
  'X-Wap-Profile',
  'Proxy-Connection',
  'X-UIDH',
  'X-Csrf-Token',
];
