export const comparators = [
  'equals: 等于',
  'not_equals: 不等于',
  'contains: 包含',
  'startswith: 以...开头',
  'endswith: 以...结尾',
  'contained_by: 实际结果是否被包含在预期结果中',
  'less_than: 小于',
  'less_than_or_equals: 小于等于',
  'greater_than: 大于',
  'greater_than_or_equals: 大于等于',
  'string_equals: 字符串相等',
  'length_equals: 长度等于',
  'length_greater_than: 长度大于',
  'length_greater_than_or_equals: 长度大于等于',
  'length_less_than: 长度小于',
  'length_less_than_or_equals: 长度小于等于',
  'type_match: 类型是否匹配',
  'regex_match: 字符串是否符合正则表达式匹配规则',
];
